# Generated by Django 5.1.4 on 2026-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='assessment_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='ats_feedback',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='ats_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='suggested_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
